export const primaryHost = 'github.com'
export const cdnHost = 'raw.githubusercontent.com'
export const apiHost = 'api.github.com'
export const org = 'cssinjs'
export const token = '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'
