export const primaryDomain = 'github.com'
export const cdnDomain = 'raw.githubusercontent.com'
export const apiDomain = 'api.github.com'
export const org = 'cssinjs'
export const token = '84f9d02a430cb688a2fbe568a9c0ce0ef0de9745'
